### ISSUE TITLE
生效和捐赠问题

### ISSUE THREAD

**Issue by TingTing1990** [Xposed-Modules-Repo/com.plus.dy#2]
你好，想问几个问题：
1、是要登录抖音帐号模块才能生效吗？
2、模块是否能防止网传“首页”“+”的烧屏情况
3、想捐赠但是找不到入口，还有绑定帐号是什么情况？

谢谢！

**Comment by javaeryang** [comment]
1，需捐赠账户，
2，不清楚烧屏啥意思
3，逗音分享对话框

**Comment by TingTing1990** [comment]
感谢，
1.3、就是要登录自己的登录帐号，然后分享对话框捐赠？
2、就是类似于 https://www.appinn.com/douyin-shaoping-tasker/

**Comment by javaeryang** [comment]
全屏沉浸，移除了底部按钮，按该文章说法，可能比该脚本更有效。

**Comment by TingTing1990** [comment]
多谢，关于捐赠我的1.3说的对的吗？先要登录你的抖音帐号（不登录也行？）然后通过大哥说的3，逗音分享对话框

还有一个问题：此模块可以内置到抖音App里吗？（比如LSPatch）

**Comment by javaeryang** [comment]
不便透露了，自行体验，框架问题需要自己处理，我这边不解决任何框架/虚拟框架问题。自己尝试会取得结果
